services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  response-generator:
    build:
      context: .
      dockerfile: app/generator/Dockerfile
    container_name: response-generator
    depends_on:
      - redis-server

  anomaly-detector:
    build:
      context: .
      dockerfile: app/detector/Dockerfile
    container_name: anomaly-detector
    depends_on:
      - redis-server
